version: '3'

services: 
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017

  app:
    container_name: node-api
    restart: always
    build: .
    ports:
      - 3000:3000
    depends_on: 
      - mongo
    links:
      - mongo